# Generated by Django 5.0.6 on 2024-05-09 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CargoPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_corrida', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipe', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Robo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
                ('id_equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='RoboSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_ativacao', models.DateField()),
                ('id_robo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.robo')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensores', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cargo')),
                ('id_equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.equipe')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='cargopermissao',
            name='id_permissao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.permissao'),
        ),
        migrations.AddField(
            model_name='corrida',
            name='id_pista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.pista'),
        ),
        migrations.AddField(
            model_name='corrida',
            name='id_robos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.robo'),
        ),
        migrations.AddField(
            model_name='robosensor',
            name='id_sensores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.sensor'),
        ),
    ]
