# Generated by Django 4.2.13 on 2024-05-27 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_cargo_cargopermissao_corrida_equipe_permissao_pista_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pista',
            old_name='equipe',
            new_name='pista',
        ),
    ]
