# Generated by Django 4.2.13 on 2024-05-31 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_equipe_pista_pista'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='D',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='I',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='P',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='tempo',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='id_pista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.pista'),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='id_robos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.robo'),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='log_corrida',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
